# Generated by Django 5.2.17 on 2026-09-07 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masterdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("lot_no", models.CharField(max_length=64)),
                ("qty_on_hand", models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                "db_table": "stock_balances",
                "ordering": ["item_id", "location_id", "lot_no"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("txn_no", models.CharField(max_length=32, unique=True)),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("receipt", "รับเข้า"),
                            ("issue_to_wo", "เบิกเข้าใบสั่งผลิต"),
                            ("return_from_wo", "คืนจากใบสั่งผลิต"),
                            ("wo_output", "รับผลผลิตเข้าคลัง"),
                            ("transfer", "โอนย้าย"),
                            ("adjustment", "ปรับปรุงยอด"),
                            ("delivery", "ส่งของ"),
                            ("scrap", "ตัดของเสีย"),
                            ("consume_from_wip", "ตัดวัตถุดิบออกจาก WIP ตอนปิดงาน"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("doc_no", models.CharField(blank=True, db_index=True, max_length=32)),
                ("doc_line_id", models.IntegerField(blank=True, null=True)),
                ("lot_no", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "serial_no",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("qty_base", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("posted_at", models.DateTimeField(db_index=True)),
                ("client_ref", models.UUIDField(db_index=True)),
                ("client_seq", models.PositiveSmallIntegerField(default=1)),
                ("is_auto_backflush", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing",
                        to="masterdata.location",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to="masterdata.item",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming",
                        to="masterdata.location",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.uom",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stock_transactions",
                "ordering": ["posted_at", "txn_no"],
                "indexes": [
                    models.Index(
                        fields=["item", "from_location", "lot_no"],
                        name="stx_item_from_lot",
                    ),
                    models.Index(
                        fields=["item", "to_location", "lot_no"], name="stx_item_to_lot"
                    ),
                    models.Index(fields=["doc_type", "doc_no"], name="stx_doc"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client_ref", "client_seq"), name="uniq_client_ref_seq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("qty__gt", 0)),
                        name="stock_txn_qty_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("qty_base__gt", 0)),
                        name="stock_txn_qty_base_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_location", models.F("to_location")), _negated=True
                        ),
                        name="stock_txn_locations_distinct",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("txn_type__in", ["receipt", "wo_output"]),
                                ("from_location__isnull", True),
                                ("to_location__isnull", False),
                            ),
                            models.Q(
                                ("txn_type__in", ["delivery", "consume_from_wip"]),
                                ("from_location__isnull", False),
                                ("to_location__isnull", True),
                            ),
                            models.Q(
                                ("txn_type", "adjustment"),
                                models.Q(
                                    models.Q(
                                        ("from_location__isnull", True),
                                        ("to_location__isnull", False),
                                    ),
                                    models.Q(
                                        ("from_location__isnull", False),
                                        ("to_location__isnull", True),
                                    ),
                                    _connector="OR",
                                ),
                            ),
                            models.Q(
                                (
                                    "txn_type__in",
                                    [
                                        "issue_to_wo",
                                        "return_from_wo",
                                        "transfer",
                                        "scrap",
                                    ],
                                ),
                                ("from_location__isnull", False),
                                ("to_location__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="stock_txn_direction_valid",
                    ),
                ],
            },
        ),
    ]
