# Generated by Django 5.2.17 on 2026-09-07 01:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masterdata", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(db_index=True, max_length=32)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True)),
                ("wo_no", models.CharField(max_length=32, unique=True)),
                ("qty_planned", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "qty_completed",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty_scrapped",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("due_date", models.DateField()),
                ("snapshot_date", models.DateField()),
                ("bom_revision", models.CharField(blank=True, max_length=16)),
                ("routing_revision", models.CharField(blank=True, max_length=16)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="masterdata.item",
                    ),
                ),
                (
                    "output_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.location",
                    ),
                ),
                (
                    "scrap_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.location",
                    ),
                ),
                (
                    "source_sales_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="sales.salesorderline",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.uom",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wip_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.location",
                    ),
                ),
            ],
            options={
                "db_table": "work_orders",
                "ordering": ["-due_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ShopFloorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_ref", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "qty_good",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty_scrap",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(db_index=True)),
                ("shift", models.CharField(blank=True, max_length=8)),
                ("has_exception", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scrap_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.scrapreason",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.workcenter",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="production.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "shop_floor_reports",
                "ordering": ["-posted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_no", models.PositiveIntegerField()),
                ("qty_per", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "scrap_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("qty_required", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "standard_unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("bom_level", models.PositiveSmallIntegerField(default=1)),
                ("source_bom_header_id", models.IntegerField(blank=True, null=True)),
                ("source_bom_line_id", models.IntegerField(blank=True, null=True)),
                ("bom_revision", models.CharField(blank=True, max_length=16)),
                (
                    "component_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.item",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.uom",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="production.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "work_order_materials",
                "ordering": ["work_order_id", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="BackflushException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qty_short", models.DecimalField(decimal_places=4, max_digits=18)),
                ("detail", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.uom",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="backflush_exceptions",
                        to="production.shopfloorreport",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="production.workorder",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="production.workordermaterial",
                    ),
                ),
            ],
            options={
                "db_table": "backflush_exceptions",
                "ordering": ["resolved_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=128)),
                (
                    "setup_minutes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "run_minutes_per_unit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "labor_rate_per_hour",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "overhead_rate_per_hour",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty_good",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty_scrap",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "actual_minutes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอผลิต"),
                            ("in_progress", "กำลังผลิต"),
                            ("completed", "เสร็จแล้ว"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "source_routing_header_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "source_routing_operation_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("routing_revision", models.CharField(blank=True, max_length=16)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.workcenter",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="production.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "work_order_operations",
                "ordering": ["work_order_id", "sequence"],
            },
        ),
        migrations.AddField(
            model_name="shopfloorreport",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="production.workorderoperation",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(blank=True, max_length=32)),
                ("to_status", models.CharField(max_length=32)),
                ("changed_at", models.DateTimeField()),
                ("note", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_history",
                        to="production.workorder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "work_order_status_history",
                "ordering": ["changed_at", "id"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_planned__gt", 0)), name="wo_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="workordermaterial",
            constraint=models.UniqueConstraint(
                fields=("work_order", "line_no"), name="uniq_wo_material_line"
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderoperation",
            constraint=models.UniqueConstraint(
                fields=("work_order", "sequence"), name="uniq_wo_operation_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="shopfloorreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_good__gte", 0), ("qty_scrap__gte", 0)),
                name="shop_floor_qty_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="shopfloorreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("qty_good__gt", 0), ("qty_scrap__gt", 0), _connector="OR"
                ),
                name="shop_floor_qty_not_all_zero",
            ),
        ),
    ]
