# Generated by Django 5.2.17 on 2026-09-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BomHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.CharField(max_length=16)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "ร่าง"),
                            ("active", "ใช้งาน"),
                            ("obsolete", "เลิกใช้"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "bom_headers",
                "ordering": ["item__code", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="BomLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField(default=10)),
                (
                    "qty_per",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="ปริมาณต่อสินค้าแม่ 1 หน่วยนับหลัก",
                        max_digits=18,
                    ),
                ),
                (
                    "scrap_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
            ],
            options={
                "db_table": "bom_lines",
                "ordering": ["bom_id", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="RoutingHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.CharField(max_length=16)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "ร่าง"),
                            ("active", "ใช้งาน"),
                            ("obsolete", "เลิกใช้"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "routing_headers",
                "ordering": ["item__code", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="RoutingOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=128)),
                (
                    "setup_minutes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "run_minutes_per_unit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
            ],
            options={
                "db_table": "routing_operations",
                "ordering": ["routing_id", "sequence"],
            },
        ),
    ]
