# Generated by Django 5.2.17 on 2026-09-07 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bom", "0001_initial"),
        ("masterdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bomheader",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bomheader",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boms",
                to="masterdata.item",
            ),
        ),
        migrations.AddField(
            model_name="bomheader",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="alternate_of_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternates",
                to="bom.bomline",
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="bom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="bom.bomheader",
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="component_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="used_in_boms",
                to="masterdata.item",
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="uom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masterdata.uom",
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routingheader",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routingheader",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="routings",
                to="masterdata.item",
            ),
        ),
        migrations.AddField(
            model_name="routingheader",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routingoperation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routingoperation",
            name="routing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="bom.routingheader",
            ),
        ),
        migrations.AddField(
            model_name="routingoperation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routingoperation",
            name="work_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="masterdata.workcenter",
            ),
        ),
        migrations.AddConstraint(
            model_name="bomheader",
            constraint=models.UniqueConstraint(
                fields=("item", "revision"), name="uniq_bom_item_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="bomheader",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="bom_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="bomline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_per__gt", 0)), name="bom_line_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="bomline",
            constraint=models.CheckConstraint(
                condition=models.Q(("scrap_pct__gte", 0), ("scrap_pct__lt", 100)),
                name="bom_line_scrap_pct_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingheader",
            constraint=models.UniqueConstraint(
                fields=("item", "revision"), name="uniq_routing_item_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="routingheader",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="routing_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingoperation",
            constraint=models.UniqueConstraint(
                fields=("routing", "sequence"), name="uniq_routing_sequence"
            ),
        ),
    ]
